name: smart-3seq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools=1.9
  - cutadapt=1.18
  - htslib=1.9
  - libdeflate=1.0
  - pysam=0.15.2
  - samtools=1.9
  - snakemake=5.4.0
  - snakemake-minimal=5.4.0
  - star=2.6.1b
  - subread=1.6.3
  - xopen=0.4.1
  - aioeasywebdav=2.2.0
  - aiohttp=3.4.4
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - async-timeout=3.0.1
  - attrs=18.2.0
  - bcrypt=3.1.4
  - boto3=1.9.79
  - botocore=1.12.79
  - bz2file=0.98
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - cachetools=2.1.0
  - cairo=1.14.12
  - certifi=2019.3.9
  - cffi=1.11.5
  - chardet=3.0.4
  - configargparse=0.13.0
  - cryptography=2.6.1
  - curl=7.64.0
  - decorator=4.3.0
  - docutils=0.14
  - dropbox=9.2.0
  - expat=2.2.5
  - filechunkio=1.8
  - fontconfig=2.13.1
  - freetype=2.9.1
  - ftputil=3.4
  - gettext=0.19.8.1
  - gitdb2=2.0.5
  - gitpython=2.1.11
  - glib=2.56.2
  - google-api-core=0.1.4
  - google-auth=1.6.2
  - google-cloud-core=0.28.1
  - google-cloud-storage=1.13.0
  - google-resumable-media=0.3.2
  - googleapis-common-protos=1.5.5
  - graphite2=1.3.13
  - graphviz=2.38.0
  - harfbuzz=1.9.0
  - icu=58.2
  - idna=2.8
  - idna_ssl=1.1.0
  - jinja2=2.10
  - jmespath=0.9.3
  - jpeg=9c
  - jsonschema=3.0.0a3
  - krb5=1.16.3
  - libcurl=7.64.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=7.3.0
  - libgfortran-ng=7.2.0
  - libiconv=1.15
  - libpng=1.6.36
  - libprotobuf=3.6.1
  - libssh2=1.8.0
  - libstdcxx-ng=7.3.0
  - libtiff=4.0.10
  - libtool=2.4.6
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.8
  - llvmlite=0.26.0
  - markupsafe=1.1.0
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - multidict=4.5.2
  - ncurses=6.1
  - networkx=2.2
  - numba=0.41.0
  - openblas=0.3.3
  - openssl=1.1.1b
  - pandas=0.23.4
  - pango=1.40.14
  - paramiko=2.4.2
  - pcre=8.41
  - pigz=2.3.4
  - pip=18.1
  - pixman=0.34.0
  - prettytable=0.7.2
  - protobuf=3.6.1
  - psutil=5.4.8
  - pthread-stubs=0.4
  - pyasn1=0.4.4
  - pyasn1-modules=0.2.3
  - pycparser=2.19
  - pygraphviz=1.5
  - pynacl=1.3.0
  - pyopenssl=18.0.0
  - pyrsistent=0.14.9
  - pysftp=0.2.9
  - pysocks=1.6.8
  - python=3.6.7
  - python-dateutil=2.7.5
  - python-irodsclient=0.7.0
  - pytz=2018.9
  - pyyaml=3.13
  - ratelimiter=1.2.0
  - readline=7.0
  - requests=2.21.0
  - rsa=3.4.2
  - s3transfer=0.1.13
  - setuptools=40.6.3
  - six=1.12.0
  - smmap2=2.0.5
  - sqlite=3.26.0
  - tk=8.6.9
  - urllib3=1.24.1
  - wheel=0.32.3
  - wrapt=1.11.0
  - xmlrunner=1.7.7
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.6
  - xorg-libxau=1.0.8
  - xorg-libxdmcp=1.1.2
  - xorg-libxext=1.3.3
  - xorg-libxpm=3.5.12
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - yarl=1.3.0
  - zlib=1.2.11
  - blas=1.0
  - datrie=0.7.1
  - intel-openmp=2019.1
  - mkl=2019.1
  - numpy=1.15.4
  - numpy-base=1.15.4
