name: smart-3seq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools=1.9
  - cutadapt=1.18
  - htslib=1.9
  - libdeflate=1.0
  - pysam=0.15.2
  - samtools=1.9
  - snakemake=5.4.0
  - snakemake-minimal=5.4.0
  - star=2.6.1b
  - subread=1.6.3
  - xopen=0.4.1
  - numba=0.44.1
