# Sample information
SAMPLES:
  - "RA-058-S6_S8_L008_R1_001"
  - "RA1-S6-011_S9_L008_R1_001"

RG_NAME: "190604_DCIS_LCM_regions"

# Adapter sequences
ADAPTER_3_PRIME: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC"
ADAPTER_5_PRIME: "ATCTCGTATGCCGTCTTCTGCTTG"

# 3SEQ-tools parameters
N: "5"
G: "3"
A: "8"
M: "1"

# Other parameters
ML: "5"

# Reference info
REF_GENOME: "/scratch/dana/star_ref/GRCh38.primary_assembly.genome.fa"
GTF: "/scratch/dana/star_ref/gencode.v26.primary_assembly.annotation.gtf"
STAR_DIR: "/scratch/dana/star_ref"
TEMP_DIR: "/scratch/dana/_STARtmp"

# Software
THREE_SEQ: "./3SEQtools"
UMI_TOOLS: "./umi-dedup"

# CPU information
RAM: "2000000000"

# Project directory, must exist
PROJECT_DIR: "/scratch/dana/example/3seq_DCIS_reg"

# Fastq directory
FASTQ_DIR: "/scratch/dana/example/3seq_DCIS_reg/fastq"
