# Sample information
SAMPLES:
  - "Sample_1"
  - "Sample_2"
  - "Sample_3"
  - "Sample_4"

# Lane number which matches your fastq file
LANE: "L001"

# Read group names to use in bam files
RG_NAME: "PROJECT_NAME"

# Adapter sequences
ADAPTER_3_PRIME: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC" 
ADAPTER_5_PRIME: "ATCTCGTATGCCGTCTTCTGCTTG"

# 3SEQ-tools parameters
N: "5"  # Length of UMI
G: "3"  # Length of G-overhang
A: "8"  # Minimum length of homopolymer detection
M: "1"  # Number of mismatches allowed

# Reference info
REF_GENOME: "../data/references/genome.fa"
GTF: "../data/references/annotation.gtf"
STAR_DIR: "../data/references/star_ref"
TEMP_DIR: "../data/references/_STARtmp"

# Additional software
THREE_SEQ_TOOLS_DIR: "./3SEQtools"

# CPU information
RAM: "2147483648"

# Project directory
FASTQ_DIR: "../data/fastq"
PROJECT_DIR: "../output/"
